#./usr/bin/env  

echo "                                                          __________________                                       "
echo "                                                         |                  |                                      "                      
echo "                                                         |  !! WARNING !!   |                                      "
echo "                                                         |__________________|                                      "
echo "                                                                                                                   "
echo "                    This script will NOT compile to production standard on                                         "   
echo "                    disk(only in memory) when files are saved while running.                                       "
echo "                                                                                                                   "
echo "                !!! What this means: dev:server script requires manual client-side refresh     !!!                 "
echo "                !!! as opposed to auto-refresh on save when using other testing environments   !!!                 "
echo "                                                                                                                   "
echo "              ____________________________________________________________________________________________________ "  
echo "             |                                                                                                    |"
echo "             |    Documentation: https://webpack.js.org/guides/development/#using-webpack-dev-server              |"
echo "             |                                                                                                    |"
echo "             |   webpack-dev-server doesnt write any output files after compiling. Instead, it keeps bundle echo  |"   
echo "             |   files in memory and serves them as if they were real files mounted at the server's root path.    |"
echo "             |____________________________________________________________________________________________________|"
echo "                                                                                                                   "
echo "              PLEASE execute \`npm run webpack\` (be mindful of the \`dev_mode:\` flag that toggles dev/prod mode) "
echo "              ____________________________________________________________________________________________________ "  
echo "             |                                                                                                    |"
echo "             |     !! Compile before going to into your personal dev server/testing environment of choice !!      |"
echo "             |____________________________________________________________________________________________________|"  
